export PS1='\[\033[01;33m\]\u\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
export PS2='> '
export PS4='+ '

export LANG=en_US.UTF-8
export TERM=linux
export USER=`whoami`
export HOME=~

if [ `uname` = FreeBSD ]; then
	export PATH=$PATH:/usr/local/bin
	alias ls='ls -G'
fi

if [ `uname` = Linux ]; then
	alias ls='ls --color'
fi

if [ `uname` = Darwin ]; then
	alias ls='ls -G'
fi

echo Welcome to terminal emulator'!'
echo Output handling is based on selectel pyte library. Enjoy'!'
